services:
  - type: web
    name: ticket-system
    env: node
    plan: free
    branch: main

    buildCommand: |
      npm install
      cd client
      npm install
      npm run build

    startCommand: npm start

    envVars:
      - key: NODE_VERSION
        value: 20